baseURL = "https://poetry.faillearnrepeat.net"
theme = "hugo-bearblog"
title = "Андрюша пишет стихи"
author = "Андрей Гончаров"
languageCode = "ru"
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Иногда в рифму"
  title = "Андрюша пишет стихи"

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
